services:
#    AppBundle.example:
#        class: OC\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    AppBundle.CheckSchedule:
        class: AppBundle\CheckSchedule\CheckSchedule
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Schedule')"]

    AppBundle.CheckPrice:
        class: AppBundle\CheckPrice\CheckPrice
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Price')"]

    AppBundle.SaveBook:
        class: AppBundle\SaveBook\SaveBook
        arguments: ['@doctrine.orm.entity_manager']
